name: 'Security Check'
description: 'Scans container images for security vulnerabilities and fails on critical/high severity issues'

inputs:
  image:
    description: 'Docker image to scan (e.g., nginx:latest or myorg/myimage:v1.0.0)'
    required: true
  severity:
    description: 'Comma-separated list of severities to fail on (CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN)'
    required: false
    default: 'CRITICAL,HIGH'
  format:
    description: 'Output format for Trivy scan results (table, json, sarif, template)'
    required: false
    default: 'table'
  trivy-version:
    description: 'Version of Trivy to use'
    required: false
    default: 'latest'
  ignore-unfixed:
    description: 'Ignore vulnerabilities without fixes'
    required: false
    default: 'false'
  timeout:
    description: 'Timeout for Trivy scan (e.g., 5m, 10m)'
    required: false
    default: '5m'

outputs:
  scan-result:
    description: 'Result of the security scan (passed/failed)'
    value: ${{ steps.scan.outputs.result }}
  vulnerabilities-found:
    description: 'Total number of vulnerabilities found'
    value: ${{ steps.scan.outputs.vuln_count }}
  fixed-vulnerabilities:
    description: 'Number of vulnerabilities with fixes available'
    value: ${{ steps.scan.outputs.fixed_vuln_count }}
  unfixed-vulnerabilities:
    description: 'Number of vulnerabilities without fixes'
    value: ${{ steps.scan.outputs.unfixed_vuln_count }}

runs:
  using: 'composite'
  steps:
    # =============================================================================
    # SETUP PHASE - Install Trivy scanner
    # =============================================================================
    - name: 🔧 Install Trivy
      shell: bash
      run: |
        echo "📦 Installing Trivy security scanner..."
        
        # Install Trivy based on OS
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install aquasecurity/trivy/trivy
        elif [ "$RUNNER_OS" == "Windows" ]; then
          choco install trivy
        fi
        
        echo "✅ Trivy installed successfully!"
        trivy --version

    - name: 📊 Update Trivy vulnerability database
      shell: bash
      run: |
        echo "🔄 Updating Trivy vulnerability database..."
        trivy image --download-db-only
        echo "✅ Database updated successfully!"

    # =============================================================================
    # SCANNING PHASE - Scan the image for vulnerabilities
    # =============================================================================
    - name: 🔍 Scan image for vulnerabilities
      shell: bash
      id: scan
      continue-on-error: true
      run: |
        echo "🚀 Starting security scan for image: ${{ inputs.image }}"
        echo "⚙️  Severity threshold: ${{ inputs.severity }}"
        echo "⏱️  Timeout: ${{ inputs.timeout }}"
        echo "🔧 Ignore unfixed: ${{ inputs.ignore-unfixed }}"
        echo
        
        # Create output directory
        mkdir -p trivy-results
        
        # Disable exit on error to capture exit codes
        # The --exit-code 1 flag makes Trivy return exit code 1 when vulnerabilities
        # matching the severity filter are found. We use set +e to capture this exit
        # code without terminating the script early, allowing us to generate reports
        # and summaries before failing the workflow.
        set +e
        
        # Run Trivy scan with JSON output for parsing
        # Note: We always scan without --ignore-unfixed first to get all vulnerabilities
        echo "📝 Running Trivy scan..."
        trivy image \
          --exit-code 0 \
          --severity "${{ inputs.severity }}" \
          --format json \
          --output trivy-results/scan-results.json \
          --timeout "${{ inputs.timeout }}" \
          "${{ inputs.image }}"
        
        TRIVY_EXIT=$?
        
        # Also generate human-readable table output for display
        trivy image \
          --exit-code 0 \
          --severity "${{ inputs.severity }}" \
          --format table \
          --timeout "${{ inputs.timeout }}" \
          "${{ inputs.image }}" | tee trivy-results/scan-table.txt
        
        # Re-enable exit on error
        set -e
        
        # Parse results and separate fixed vs unfixed vulnerabilities
        if [ -f trivy-results/scan-results.json ]; then
          # Count total vulnerabilities
          TOTAL_VULN_COUNT=$(jq '[.Results[]?.Vulnerabilities // [] | length] | add // 0' trivy-results/scan-results.json)
          
          # Count vulnerabilities with fixes (FixedVersion is not empty/null)
          FIXED_VULN_COUNT=$(jq '[.Results[]?.Vulnerabilities // [] | .[] | select(.FixedVersion != null and .FixedVersion != "")] | length' trivy-results/scan-results.json)
          
          # Count unfixed vulnerabilities
          UNFIXED_VULN_COUNT=$(jq '[.Results[]?.Vulnerabilities // [] | .[] | select(.FixedVersion == null or .FixedVersion == "")] | length' trivy-results/scan-results.json)
          
          echo "vuln_count=$TOTAL_VULN_COUNT" >> $GITHUB_OUTPUT
          echo "fixed_vuln_count=$FIXED_VULN_COUNT" >> $GITHUB_OUTPUT
          echo "unfixed_vuln_count=$UNFIXED_VULN_COUNT" >> $GITHUB_OUTPUT
          
          if [ "$TOTAL_VULN_COUNT" -gt 0 ]; then
            echo "⚠️  Found $TOTAL_VULN_COUNT total vulnerabilities"
            echo "   - $FIXED_VULN_COUNT with fixes available"
            echo "   - $UNFIXED_VULN_COUNT without fixes"
          else
            echo "✅ No vulnerabilities found!"
          fi
        else
          echo "vuln_count=0" >> $GITHUB_OUTPUT
          echo "fixed_vuln_count=0" >> $GITHUB_OUTPUT
          echo "unfixed_vuln_count=0" >> $GITHUB_OUTPUT
        fi
        
        # Determine exit code based on ignore-unfixed setting
        SCAN_EXIT_CODE=0
        if [ "${{ inputs.ignore-unfixed }}" = "true" ]; then
          # When ignore-unfixed is true, only fail on vulnerabilities with fixes
          if [ "$FIXED_VULN_COUNT" -gt 0 ]; then
            echo "❌ Found $FIXED_VULN_COUNT vulnerabilities with fixes available"
            SCAN_EXIT_CODE=1
          else
            echo "✅ No fixable vulnerabilities found (unfixed vulnerabilities are ignored)"
          fi
        else
          # When ignore-unfixed is false, fail on any vulnerability
          if [ "$TOTAL_VULN_COUNT" -gt 0 ]; then
            echo "❌ Found $TOTAL_VULN_COUNT vulnerabilities"
            SCAN_EXIT_CODE=1
          fi
        fi
        
        # Set result based on exit code
        if [ $SCAN_EXIT_CODE -eq 0 ]; then
          echo "result=passed" >> $GITHUB_OUTPUT
        else
          echo "result=failed" >> $GITHUB_OUTPUT
        fi
        
        exit $SCAN_EXIT_CODE

    # =============================================================================
    # ANNOTATION PHASE - Create GitHub annotations for findings
    # =============================================================================
    - name: 📋 Generate annotations for vulnerabilities
      shell: bash
      if: always() && hashFiles('trivy-results/scan-results.json') != ''
      run: |
        echo "📝 Creating GitHub annotations for vulnerabilities..."
        
        # Parse JSON and create annotations with fix status
        jq -r '.Results[]? | select(.Vulnerabilities != null) | .Vulnerabilities[] | 
          # Determine fix status
          (if (.FixedVersion != null and .FixedVersion != "") then " [Fix: " + .FixedVersion + "]" else " [UNFIXED]" end) as $fixStatus |
          # Create annotation based on severity
          if .Severity == "CRITICAL" or .Severity == "HIGH" then
            "::error title=" + .Severity + " - " + .VulnerabilityID + "::" + .PkgName + " " + (.InstalledVersion // "unknown") + $fixStatus + " - " + (.Title // .Description // "No description")
          elif .Severity == "MEDIUM" then
            "::warning title=" + .Severity + " - " + .VulnerabilityID + "::" + .PkgName + " " + (.InstalledVersion // "unknown") + $fixStatus + " - " + (.Title // .Description // "No description")
          else
            "::notice title=" + .Severity + " - " + .VulnerabilityID + "::" + .PkgName + " " + (.InstalledVersion // "unknown") + $fixStatus + " - " + (.Title // .Description // "No description")
          end' trivy-results/scan-results.json || echo "No vulnerabilities to annotate"

    # =============================================================================
    # SUMMARY PHASE - Create job summary
    # =============================================================================
    - name: 📊 Create security scan summary
      shell: bash
      if: always() && hashFiles('trivy-results/scan-results.json') != ''
      run: |
        echo "📄 Creating job summary..."
        
        {
          echo "# 🔒 Security Scan Results"
          echo
          echo "**Image:** \`${{ inputs.image }}\`"
          echo "**Ignore Unfixed:** \`${{ inputs.ignore-unfixed }}\`"
          echo
          echo "## Vulnerability Summary"
          echo
          
          # Count vulnerabilities by severity (all vulnerabilities)
          CRITICAL=$(jq '[.Results[]?.Vulnerabilities // [] | .[] | select(.Severity == "CRITICAL")] | length' trivy-results/scan-results.json)
          HIGH=$(jq '[.Results[]?.Vulnerabilities // [] | .[] | select(.Severity == "HIGH")] | length' trivy-results/scan-results.json)
          MEDIUM=$(jq '[.Results[]?.Vulnerabilities // [] | .[] | select(.Severity == "MEDIUM")] | length' trivy-results/scan-results.json)
          LOW=$(jq '[.Results[]?.Vulnerabilities // [] | .[] | select(.Severity == "LOW")] | length' trivy-results/scan-results.json)
          UNKNOWN=$(jq '[.Results[]?.Vulnerabilities // [] | .[] | select(.Severity == "UNKNOWN")] | length' trivy-results/scan-results.json)
          
          # Count fixed vulnerabilities by severity
          CRITICAL_FIXED=$(jq '[.Results[]?.Vulnerabilities // [] | .[] | select(.Severity == "CRITICAL" and .FixedVersion != null and .FixedVersion != "")] | length' trivy-results/scan-results.json)
          HIGH_FIXED=$(jq '[.Results[]?.Vulnerabilities // [] | .[] | select(.Severity == "HIGH" and .FixedVersion != null and .FixedVersion != "")] | length' trivy-results/scan-results.json)
          MEDIUM_FIXED=$(jq '[.Results[]?.Vulnerabilities // [] | .[] | select(.Severity == "MEDIUM" and .FixedVersion != null and .FixedVersion != "")] | length' trivy-results/scan-results.json)
          LOW_FIXED=$(jq '[.Results[]?.Vulnerabilities // [] | .[] | select(.Severity == "LOW" and .FixedVersion != null and .FixedVersion != "")] | length' trivy-results/scan-results.json)
          UNKNOWN_FIXED=$(jq '[.Results[]?.Vulnerabilities // [] | .[] | select(.Severity == "UNKNOWN" and .FixedVersion != null and .FixedVersion != "")] | length' trivy-results/scan-results.json)
          
          # Count unfixed vulnerabilities by severity
          CRITICAL_UNFIXED=$((CRITICAL - CRITICAL_FIXED))
          HIGH_UNFIXED=$((HIGH - HIGH_FIXED))
          MEDIUM_UNFIXED=$((MEDIUM - MEDIUM_FIXED))
          LOW_UNFIXED=$((LOW - LOW_FIXED))
          UNKNOWN_UNFIXED=$((UNKNOWN - UNKNOWN_FIXED))
          
          echo "| Severity | Total | Fixable | Unfixed |"
          echo "|----------|-------|---------|---------|"
          echo "| 🔴 Critical | $CRITICAL | $CRITICAL_FIXED | $CRITICAL_UNFIXED |"
          echo "| 🟠 High | $HIGH | $HIGH_FIXED | $HIGH_UNFIXED |"
          echo "| 🟡 Medium | $MEDIUM | $MEDIUM_FIXED | $MEDIUM_UNFIXED |"
          echo "| 🟢 Low | $LOW | $LOW_FIXED | $LOW_UNFIXED |"
          echo "| ⚪ Unknown | $UNKNOWN | $UNKNOWN_FIXED | $UNKNOWN_UNFIXED |"
          echo
          
          # Determine scan status based on ignore-unfixed setting
          FAIL_SEVERITIES="${{ inputs.severity }}"
          SHOULD_FAIL=false
          
          if [ "${{ inputs.ignore-unfixed }}" = "true" ]; then
            # When ignore-unfixed is true, only fail on fixable vulnerabilities
            if [[ "$FAIL_SEVERITIES" == *"CRITICAL"* ]] && [ "$CRITICAL_FIXED" -gt 0 ]; then
              SHOULD_FAIL=true
            fi
            if [[ "$FAIL_SEVERITIES" == *"HIGH"* ]] && [ "$HIGH_FIXED" -gt 0 ]; then
              SHOULD_FAIL=true
            fi
            if [[ "$FAIL_SEVERITIES" == *"MEDIUM"* ]] && [ "$MEDIUM_FIXED" -gt 0 ]; then
              SHOULD_FAIL=true
            fi
            if [[ "$FAIL_SEVERITIES" == *"LOW"* ]] && [ "$LOW_FIXED" -gt 0 ]; then
              SHOULD_FAIL=true
            fi
          else
            # When ignore-unfixed is false, fail on any vulnerability
            if [[ "$FAIL_SEVERITIES" == *"CRITICAL"* ]] && [ "$CRITICAL" -gt 0 ]; then
              SHOULD_FAIL=true
            fi
            if [[ "$FAIL_SEVERITIES" == *"HIGH"* ]] && [ "$HIGH" -gt 0 ]; then
              SHOULD_FAIL=true
            fi
            if [[ "$FAIL_SEVERITIES" == *"MEDIUM"* ]] && [ "$MEDIUM" -gt 0 ]; then
              SHOULD_FAIL=true
            fi
            if [[ "$FAIL_SEVERITIES" == *"LOW"* ]] && [ "$LOW" -gt 0 ]; then
              SHOULD_FAIL=true
            fi
          fi
          
          if [ "$SHOULD_FAIL" = true ]; then
            echo "## ❌ Scan Result: FAILED"
            echo
            if [ "${{ inputs.ignore-unfixed }}" = "true" ]; then
              echo "**Fixable vulnerabilities detected!**"
              echo
              echo "Unfixed vulnerabilities are shown but ignored in the failure check."
            else
              echo "**Critical or high severity vulnerabilities detected!**"
            fi
            echo
            echo "Failing severities: \`${{ inputs.severity }}\`"
          else
            echo "## ✅ Scan Result: PASSED"
            echo
            if [ "${{ inputs.ignore-unfixed }}" = "true" ]; then
              echo "No fixable vulnerabilities found matching the severity threshold."
              if [ "$((CRITICAL_UNFIXED + HIGH_UNFIXED + MEDIUM_UNFIXED + LOW_UNFIXED + UNKNOWN_UNFIXED))" -gt 0 ]; then
                echo
                echo "⚠️ **Note:** Unfixed vulnerabilities were found but are being ignored."
              fi
            else
              echo "No vulnerabilities found matching the severity threshold."
            fi
          fi
          
          echo
          echo "## 📋 Detailed Results"
          echo
          echo '```'
          cat trivy-results/scan-table.txt
          echo '```'
          
        } >> $GITHUB_STEP_SUMMARY

    # =============================================================================
    # ARTIFACTS PHASE - Upload scan results
    # =============================================================================
    - name: 📦 Upload scan results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: trivy-scan-results-${{ github.run_number }}
        path: |
          trivy-results/*.json
          trivy-results/*.txt
        retention-days: 30

    # =============================================================================
    # VALIDATION PHASE - Fail if critical/high vulnerabilities found
    # =============================================================================
    - name: ✅ Evaluate scan results
      shell: bash
      run: |
        SCAN_RESULT="${{ steps.scan.outputs.result }}"
        
        if [ "$SCAN_RESULT" = "failed" ]; then
          echo "❌ Security scan failed! Critical or high severity vulnerabilities detected."
          echo "📥 Scan results are available in artifacts for detailed analysis."
          exit 1
        else
          echo "✅ Security scan passed! No critical or high severity vulnerabilities found."
          echo "🎉 Image is safe to use."
        fi
